# -*- coding: utf-8 -*-
"""TareaPreviaSQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12U3oRmiK8MeVhKOocfd_l9kNQKAVpsqf
"""

# ACTIVIDAD 00
empleado_01 = [
    [20222333,45,2,20000],
    [33456234,40,0,25000],
    [45432345,41,1,10000]
]
# ACTIVIDAD 01

def superanSalarioActividad01(matriz, umbral):
  matriz_valida = []
  for fila in matriz:
    salario = fila[3]
    if salario >= umbral:
      matriz_valida.append(fila)
  return matriz_valida
print("Resultado actividad 01")
print(superanSalarioActividad01(empleado_01, 15000))
print("")

# ACTIVIDAD 02

empleado_02 = [
    [20222333,45,2,20000],
    [33456234,40,0,25000],
    [45432345,41,1,10000],
    [43967304,37,0,12000],
    [42236276,36,0,18000]
]
print("Resultado actividad 02")
print(superanSalarioActividad01(empleado_02, 15000))
print("")

# ACTIVIDAD 03

empleado_03 = [
    [20222333,20000,45,2],
    [33456234,25000,40,0],
    [45432345,10000,41,1],
    [43967304,12000,37,0],
    [42236276,18000,36,0]
]
print("Resultado actividad 03 numero 1")
print(superanSalarioActividad01(empleado_03, 15000))
print("no funciona")
print("")

def superanSalarioActividad03(matriz, umbral):
  matriz_valida = []
  for fila in matriz:
    salario = fila[1]
    if salario >= umbral:
      nueva_fila = [fila[0],fila[2],fila[3],fila[1]]
      matriz_valida.append(nueva_fila)
  return matriz_valida

print("Resultado actividad 03 numero 2")
print(superanSalarioActividad03(empleado_03, 15000))
print("")

# ACTIVIDAD 04

empleado_04 = [
    [20222333,33456234,45432345,43967304,42236276],
    [20000,25000,10000,12000,18000],
    [45,40,41,37,36],
    [2,0,1,0,0]
]
print("Resultado actividad 04 numero 1")
print(superanSalarioActividad01(empleado_04, 15000))
print("no funciona")
print("")

print("Resultado actividad 04 numero 2")
print(superanSalarioActividad03(empleado_04, 15000))
print("no funciona")
print("")

def de_columnas_a_filas(matriz):
  matriz_nueva = []
  for i in range(0,len(matriz[0])):
    nueva_fila = []
    for columna in matriz:
      nueva_fila.append(columna[i])
    matriz_nueva.append(nueva_fila)
  return matriz_nueva

def superanSalarioActividad04(matriz, umbral):
  matriz_por_filas = de_columnas_a_filas(matriz)
  return superanSalarioActividad03(matriz_por_filas, umbral)

print("Resultado actividad 04 numero 3")
print(superanSalarioActividad04(empleado_04, 15000))
print("")


"""
# ACTIVIDAD 05
1)
a_ Al agregarle mas filas no cambio en nada la programacion
b_ hubo que modificar levemente el programa cambiando la columna a analizar
2) hubo que cambiar completamente el codigo, para eso use una funcion que convierte la matriz en una por filas, asi es mas facil de trabajar
3) Seria muy util ya que simplifica el proceso, por ejemplo se podria acceder a los datos con una sola linea.
"""